# Generated by Django 3.0.6 on 2020-05-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cowsay', '0002_inputtext_cow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtext',
            name='cow',
            field=models.CharField(choices=[('default', 'default'), ('beavis.zen', 'beavis.zen'), ('blowfish', 'blowfish'), ('bud-frogs', 'bud-frogs'), ('bunny', 'bunny'), ('cheese', 'cheese'), ('cower', 'cower'), ('daemon', 'daemon'), ('dragon', 'dragon'), ('dragon-and-cow', 'dragon-and-cow'), ('elephant', 'elephant'), ('elephant-in-snake', 'elephant-in-snake'), ('eyes', 'eyes'), ('flaming-sheep', 'flaming-sheep'), ('ghostbusters', 'ghostbusters'), ('head-in', 'head-in'), ('hellokitty', 'hellokitty'), ('kiss', 'kiss'), ('kitty', 'kitty'), ('koala', 'koala'), ('kosh', 'kosh'), ('luke-koala', 'luke-koala'), ('meow', 'meow'), ('milk', 'milk'), ('moofasa', 'moofasa'), ('moose', 'moose'), ('ren', 'ren'), ('sheep', 'sheep'), ('skeleton', 'skeleton'), ('small', 'small'), ('stegosaurus', 'stegosaurus'), ('stimpy', 'stimpy'), ('supermilker', 'supermilker'), ('surgery', 'surgery'), ('telebears', 'telebears'), ('three-eyes', 'three-eyes'), ('turkey', 'turkey'), ('turtle', 'turtle'), ('tux', 'tux'), ('udder', 'udder'), ('vader', 'vader'), ('vader-koala', 'vader-koala'), ('www', 'www')], max_length=20),
        ),
    ]
